name: GitHub Actions MVC

on:
  workflow_dispatch:
    
  

jobs:
  MVC-Job:
   env:
    VRWhere_HOME: 'C:\GitHubActions\actions-runner-win-x64-2.284.0\WindowsSystem\_tool\vswhere\2.7.1\x64'
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
   
   runs-on: [self-hosted]
  
   steps:
    - uses: actions/checkout@v2
    - name: Setup VSWhere.exe
      uses: warrenbuckley/Setup-VSWhere@v1

    - name: VSWhere MSBuild
      run: vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
    #- name: Add msbuild to PATH
     # uses: microsoft/setup-msbuild@v1.1
      #with:
       #vs-version: '[16.4,16.5)'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5  
      with:
           nuget-version: '5.x'
  
    - name: Restore NuGet Packages
      run: nuget restore MVCDemo/MVCDemo/MVCDemo/MVCDemo.csproj
    - name: Build
      run: dotnet build MVCDemo.sln /p:Configuration=Release /p:Platform=\"Any CPU\" /p:DeployOnBuild=true /p:WebPublishMethod=Package 	/p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation=..\\ArtifactStaging
    - name: Test
      run: dotnet test UnitTestProject\bin\Debug\UnitTestProject.dll
      #Prepare the code for sending to Scan Zip the Code
    - name: Zip the code
      uses: papeloto/action-zip@v1
      with:
       files: GitHubMVCDemo
       recursive: false
       dest: GitHubMVCDemo.zip

#Send the code for Scan 
    - name: Send for Scan
      run:  move GitHubMVCDemo.zip D:\a\MVCDemo\MVCDemo
    

    
