name: GitHub Actions MVC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  MVC-Job:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build MVCDemo.sln /p:Configuration=Release /p:Platform=\"Any CPU\" /p:DeployOnBuild=true /p:WebPublishMethod=Package 	/p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation=..\\ArtifactStaging
    - name: Test
      run: dotnet test UnitTestProject\bin\Debug\UnitTestProject.dll
      #Prepare the code for sending to Scan Zip the Code
    - name: Zip the code
      uses: papeloto/action-zip@v1
      with:
       files: GitHubMVCDemo
       recursive: false
       dest: GitHubMVCDemo.zip

#Send the code for Scan 
    - name: Send for Scan
      run:  move GitHubMVCDemo.zip D:\a\MVCDemo\MVCDemo
    

    
