name: .NET

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build MVCDemo.sln 
    - name: Test
      run: dotnet test UnitTestProject\bin\Debug\UnitTestProject.dll
