name: MVC_two

on:
   workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      uses: EasyDesk/action-dotnet-build@v1
      with:
          # (Optional) Additional arguments for dotnet build.
          build-args: /p:Platform=\"Any CPU\" /p:DeployOnBuild=true /p:WebPublishMethod=Package 	/p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation=..\\ArtifactStaging

          # (Optional) Build configuration, defaults to 'Release'
          # If the version starts with the 'v' prefix, it will be removed to conform to the requirements of dotnet pack.
          build-configuration: Release

          # (Optional) The path of the project to build; if omitted, the whole solution is built
          path: MVCDemo.sln
    - name: Test
      run: dotnet test UnitTestProject\bin\Debug\UnitTestProject.dll
